import json
import subprocess

from nctl_core.config import Config
from nctl_core.dnsmasq_apply import (
    _inventory_group_hosts,
    _parse_recap,
    build_dnsmasq_apply,
)
from nctl_core.dnsmasq_render import DnsmasqRenderData
from nctl_core.output import Envelope


def _config(tmp_path):
    ansible_dir = tmp_path / "ansible_agdev"
    playbook = ansible_dir / "playbooks/dnsmasq/deploy_dnsmasq_records.yml"
    playbook.parent.mkdir(parents=True)
    playbook.write_text("---\n")
    inventory = ansible_dir / "inventories/generated/hosts_intent.yml"
    inventory.parent.mkdir(parents=True)
    inventory.write_text("all: {}\n")
    config_path = tmp_path / "nctl.toml"
    config_path.write_text(
        f"""
[nautobot]
url = "http://nautobot.test"

[inventory]
dumps_dir = "{tmp_path / 'dumps'}"

[events]
log_dir = "{tmp_path / 'events'}"

[ansible]
playbook_dir = "{ansible_dir}"
inventory = "inventories/generated/hosts_intent.yml"

[repo]
root = "{tmp_path}"
"""
    )
    return Config.load(config_path)


def _render(operation_id=None):
    return Envelope.build(
        "nctl.render.dnsmasq.v1",
        DnsmasqRenderData(
            schema_version="4.0",
            summary={"dns_records": 1},
            dns_records=[{"line": "host-record=edge.test,192.0.2.10"}],
            conf=(
                "# Generated by nctl\n"
                "# schema_version: 4.0\n"
                f"# operation_id: {operation_id}\n"
                "host-record=edge.test,192.0.2.10\n"
            ),
        ),
    )


def _inventory_payload():
    return {
        "dnsmasq_server": {"hosts": ["agdnsmasq"]},
        "_meta": {"hostvars": {"agdnsmasq": {}}},
    }


def test_dry_run_renders_artifact_invokes_check_diff_and_emits_events(tmp_path, monkeypatch):
    cfg = _config(tmp_path)
    calls = []
    monkeypatch.setattr("nctl_core.dnsmasq_apply.build_dnsmasq_render", lambda cfg, operation_id=None: _render(operation_id))
    monkeypatch.setattr("nctl_core.dnsmasq_apply.shutil.which", lambda name: f"/usr/bin/{name}")

    def fake_run(args, cwd):
        calls.append((args, cwd))
        if args[0] == "ansible-inventory":
            return subprocess.CompletedProcess(args, 0, json.dumps(_inventory_payload()), "")
        stdout = "PLAY RECAP ***\nagdnsmasq : ok=3 changed=1 unreachable=0 failed=0 skipped=0 rescued=0 ignored=0\n"
        return subprocess.CompletedProcess(args, 0, stdout, "")

    monkeypatch.setattr("nctl_core.dnsmasq_apply._run_command", fake_run)

    envelope = build_dnsmasq_apply(cfg)

    assert envelope.ok is True
    assert envelope.data.mode == "dry-run"
    assert envelope.data.target_hosts == ["agdnsmasq"]
    assert envelope.data.ansible.exit_code == 0
    assert envelope.data.ansible.recap["agdnsmasq"]["changed"] == 1
    assert calls[1][0][-2:] == ["--check", "--diff"]
    artifact = cfg.events.resolved_log_dir() / envelope.data.operation_id / "artifacts/dnsmasq-records.conf"
    assert artifact.is_file()
    assert f"# operation_id: {envelope.data.operation_id}" in artifact.read_text()
    events = [json.loads(line)["event"] for line in (cfg.events.resolved_log_dir() / f"{envelope.data.operation_id}.jsonl").read_text().splitlines()]
    assert events == ["started", "rendered", "dry_run_completed", "finished"]


def test_yes_runs_real_apply_without_check_flags(tmp_path, monkeypatch):
    cfg = _config(tmp_path)
    calls = []
    monkeypatch.setattr("nctl_core.dnsmasq_apply.build_dnsmasq_render", lambda cfg, operation_id=None: _render(operation_id))
    monkeypatch.setattr("nctl_core.dnsmasq_apply.shutil.which", lambda name: f"/usr/bin/{name}")

    def fake_run(args, cwd):
        calls.append(args)
        stdout = json.dumps(_inventory_payload()) if args[0] == "ansible-inventory" else "agdnsmasq : ok=3 changed=1 unreachable=0 failed=0\n"
        return subprocess.CompletedProcess(args, 0, stdout, "")

    monkeypatch.setattr("nctl_core.dnsmasq_apply._run_command", fake_run)

    envelope = build_dnsmasq_apply(cfg, apply_changes=True)

    assert envelope.ok is True
    assert envelope.data.mode == "apply"
    assert "--check" not in calls[1]
    assert "--diff" not in calls[1]
    events = [json.loads(line)["event"] for line in (cfg.events.resolved_log_dir() / f"{envelope.data.operation_id}.jsonl").read_text().splitlines()]
    assert events == ["started", "rendered", "apply_started", "apply_completed", "finished"]


def test_empty_dnsmasq_group_is_a_pointed_failure(tmp_path, monkeypatch):
    cfg = _config(tmp_path)
    monkeypatch.setattr("nctl_core.dnsmasq_apply.build_dnsmasq_render", lambda cfg, operation_id=None: _render(operation_id))
    monkeypatch.setattr("nctl_core.dnsmasq_apply.shutil.which", lambda name: f"/usr/bin/{name}")
    monkeypatch.setattr(
        "nctl_core.dnsmasq_apply._run_command",
        lambda args, cwd: subprocess.CompletedProcess(args, 0, json.dumps({"ssh_hosts": {"hosts": ["agpc"]}}), ""),
    )

    envelope = build_dnsmasq_apply(cfg)

    assert envelope.ok is False
    assert envelope.errors[0].code == "dnsmasq_inventory_group_empty"
    assert envelope.data.ansible is None


def test_ansible_failure_is_returned_with_exit_code_and_recap(tmp_path, monkeypatch):
    cfg = _config(tmp_path)
    monkeypatch.setattr("nctl_core.dnsmasq_apply.build_dnsmasq_render", lambda cfg, operation_id=None: _render(operation_id))
    monkeypatch.setattr("nctl_core.dnsmasq_apply.shutil.which", lambda name: f"/usr/bin/{name}")

    def fake_run(args, cwd):
        if args[0] == "ansible-inventory":
            return subprocess.CompletedProcess(args, 0, json.dumps(_inventory_payload()), "")
        return subprocess.CompletedProcess(
            args,
            2,
            "agdnsmasq : ok=1 changed=0 unreachable=1 failed=0 skipped=0 rescued=0 ignored=0\n",
            "unreachable",
        )

    monkeypatch.setattr("nctl_core.dnsmasq_apply._run_command", fake_run)

    envelope = build_dnsmasq_apply(cfg)

    assert envelope.ok is False
    assert envelope.errors[0].code == "ansible_dry_run_failed"
    assert envelope.data.ansible.exit_code == 2
    assert envelope.data.ansible.recap["agdnsmasq"]["unreachable"] == 1


def test_inventory_group_hosts_includes_child_groups():
    payload = {
        "dnsmasq_server": {"children": ["primary_dns"]},
        "primary_dns": {"hosts": ["dns-1", "dns-2"]},
    }
    assert _inventory_group_hosts(payload, "dnsmasq_server") == {"dns-1", "dns-2"}


def test_parse_recap_ignores_non_recap_lines():
    assert _parse_recap("TASK [x] ***\nhost-a : ok=2 changed=1 unreachable=0 failed=0\n") == {
        "host-a": {"ok": 2, "changed": 1, "unreachable": 0, "failed": 0}
    }
