import json

from typer.testing import CliRunner

import nctl_core.cli.main as main
from nctl_core.dnsmasq_render import DnsmasqRenderData
from nctl_core.output import Envelope, EnvelopeError

runner = CliRunner()


def _ok_envelope() -> Envelope[DnsmasqRenderData]:
    data = DnsmasqRenderData(
        schema_version="4.0",
        summary={"dns_records": 1, "dhcp_reservations": 0, "dhcp_ranges": 0, "skipped": {"details": 0}},
        dns_records=[{"line": "host-record=edge-1.example.test,192.0.2.10"}],
        dhcp_reservations=[],
        dhcp_ranges=[],
        skipped=[],
        conf="# Generated by nctl\nhost-record=edge-1.example.test,192.0.2.10\n",
    )
    return Envelope.build("nctl.render.dnsmasq.v2", data, [])


def _failed_envelope() -> Envelope[DnsmasqRenderData]:
    return Envelope.build(
        "nctl.render.dnsmasq.v2",
        DnsmasqRenderData(),
        [EnvelopeError(code="nautobot_fetch_failed", message="boom")],
    )


def _blocked_envelope() -> Envelope[DnsmasqRenderData]:
    """VM p3 Step 6: a `desired_mac_mismatch` conflict blocks the whole render --
    distinct from `_failed_envelope()`'s generic infra failure."""
    data = DnsmasqRenderData(
        schema_version="5.0",
        summary={"dns_records": 0, "dhcp_reservations": 0, "dhcp_ranges": 0, "skipped": {"details": 1}},
        dns_records=[],
        dhcp_reservations=[],
        dhcp_ranges=[],
        skipped=[],
        blocked=True,
        blocking_findings=[
            {
                "code": "desired_mac_mismatch",
                "desired_endpoint": "primary",
                "desired_node_slug": "edge-1",
                "desired_mac": "aa:bb:cc:dd:ee:ff",
                "actual_mac_candidates": [{"mac_address": "11:22:33:44:55:66"}],
            }
        ],
        partial_conf_preview="# Generated by nctl\n# schema_version: 5.0\n",
    )
    return Envelope.build(
        "nctl.render.dnsmasq.v3",
        data,
        [EnvelopeError(code="desired_mac_mismatch", message="edge-1/primary: desired_mac_mismatch blocks the shared dnsmasq render")],
    )


def test_render_dnsmasq_default_prints_conf_to_stdout(monkeypatch):
    monkeypatch.setattr(main, "_load_config", lambda path: object())
    monkeypatch.setattr(main, "build_dnsmasq_render", lambda cfg: _ok_envelope())

    result = runner.invoke(main.app, ["render", "dnsmasq"])

    assert result.exit_code == 0
    assert "host-record=edge-1.example.test,192.0.2.10" in result.stdout


def test_render_dnsmasq_json_prints_envelope(monkeypatch):
    monkeypatch.setattr(main, "_load_config", lambda path: object())
    monkeypatch.setattr(main, "build_dnsmasq_render", lambda cfg: _ok_envelope())

    result = runner.invoke(main.app, ["render", "dnsmasq", "--json"])

    assert result.exit_code == 0
    payload = json.loads(result.stdout)
    assert payload["schema"] == "nctl.render.dnsmasq.v2"
    assert payload["data"]["summary"]["dns_records"] == 1


def test_render_dnsmasq_out_writes_file_and_prints_summary(tmp_path, monkeypatch):
    monkeypatch.setattr(main, "_load_config", lambda path: object())
    monkeypatch.setattr(main, "build_dnsmasq_render", lambda cfg: _ok_envelope())
    out_path = tmp_path / "dnsmasq-records.conf"

    result = runner.invoke(main.app, ["render", "dnsmasq", "--out", str(out_path)])

    assert result.exit_code == 0
    assert out_path.read_text() == "# Generated by nctl\nhost-record=edge-1.example.test,192.0.2.10\n"
    assert "dns_records: 1" in result.stdout
    assert "host-record" not in result.stdout


def test_render_dnsmasq_exit_1_and_no_file_on_failure(tmp_path, monkeypatch):
    monkeypatch.setattr(main, "_load_config", lambda path: object())
    monkeypatch.setattr(main, "build_dnsmasq_render", lambda cfg: _failed_envelope())
    out_path = tmp_path / "dnsmasq-records.conf"

    result = runner.invoke(main.app, ["render", "dnsmasq", "--out", str(out_path)])

    assert result.exit_code == 1
    assert not out_path.exists()
    assert "error [nautobot_fetch_failed]" in result.stdout


def test_render_dnsmasq_blocked_leaves_pre_existing_file_untouched(tmp_path, monkeypatch):
    """VM p3 Step 6: a blocked render (distinct from a generic fetch failure)
    must not overwrite whatever was already on disk -- a stronger proof than
    just 'no file exists'."""
    monkeypatch.setattr(main, "_load_config", lambda path: object())
    monkeypatch.setattr(main, "build_dnsmasq_render", lambda cfg: _blocked_envelope())
    out_path = tmp_path / "dnsmasq-records.conf"
    pre_existing_content = "# pre-existing deployed conf, must survive untouched\n"
    out_path.write_text(pre_existing_content)

    result = runner.invoke(main.app, ["render", "dnsmasq", "--out", str(out_path)])

    assert result.exit_code == 1
    assert out_path.read_text() == pre_existing_content


def test_render_dnsmasq_blocked_json_shows_the_blocking_finding(monkeypatch):
    monkeypatch.setattr(main, "_load_config", lambda path: object())
    monkeypatch.setattr(main, "build_dnsmasq_render", lambda cfg: _blocked_envelope())

    result = runner.invoke(main.app, ["render", "dnsmasq", "--json"])

    assert result.exit_code == 1
    payload = json.loads(result.stdout)
    assert payload["ok"] is False
    assert payload["data"]["blocked"] is True
    assert payload["data"]["blocking_findings"][0]["code"] == "desired_mac_mismatch"
    assert payload["errors"][0]["code"] == "desired_mac_mismatch"
