import json
import subprocess
from pathlib import Path

from nctl_core.config import Config
from nctl_core.dnsmasq_apply import (
    _inventory_group_hosts,
    _parse_recap,
    build_dnsmasq_apply,
)
from nctl_core.dnsmasq_render import DnsmasqRenderData
from nctl_core.output import Envelope
from nctl_core.ssh_enroll import SshProbeRunner
from nctl_core.ssh_trust import build_ansible_ssh_common_args, derive_host_key_alias

NODE_ID = "27818c12-fe15-4c9f-83d0-7949523f6c33"
ALIAS = derive_host_key_alias(NODE_ID)
KEY_BLOB = "QUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUZmYWtlZWQyNTUxOWtleWJ5dGVzMDAwMDAwMDAwMDAwMDAwMA=="
OTHER_KEY_BLOB = "QUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUZmYWtlZWQyNTUxOWRpZmZlcmVudGtleWJ5dGVzMDAwMDA="


def _config(tmp_path):
    ansible_dir = tmp_path / "ansible_agdev"
    setup_playbook = ansible_dir / "playbooks/bootstrap/setup_dnsmasq.yml"
    setup_playbook.parent.mkdir(parents=True)
    setup_playbook.write_text("---\n")
    playbook = ansible_dir / "playbooks/dnsmasq/deploy_dnsmasq_records.yml"
    playbook.parent.mkdir(parents=True)
    playbook.write_text("---\n")
    inventory = ansible_dir / "inventories/generated/hosts_intent.yml"
    inventory.parent.mkdir(parents=True)
    inventory.write_text("all: {}\n")
    config_path = tmp_path / "nctl.toml"
    config_path.write_text(
        f"""
[nautobot]
url = "http://nautobot.test"

[inventory]
dumps_dir = "{tmp_path / 'dumps'}"

[events]
log_dir = "{tmp_path / 'events'}"

[ansible]
playbook_dir = "{ansible_dir}"
inventory = "inventories/generated/hosts_intent.yml"

[repo]
root = "{tmp_path}"

[ssh]
known_hosts_file = "{tmp_path / 'ssh' / 'known_hosts'}"
lock_path = "{tmp_path / 'ssh.lock'}"
"""
    )
    return Config.load(config_path)


def _render(operation_id=None):
    return Envelope.build(
        "nctl.render.dnsmasq.v1",
        DnsmasqRenderData(
            schema_version="4.0",
            summary={"dns_records": 1},
            dns_records=[{"line": "host-record=edge.test,192.0.2.10"}],
            conf=(
                "# Generated by nctl\n"
                "# schema_version: 4.0\n"
                f"# operation_id: {operation_id}\n"
                "host-record=edge.test,192.0.2.10\n"
            ),
        ),
    )


def _valid_host_vars(cfg: Config, *, ansible_host: str = "192.0.2.10") -> dict:
    return {
        "nintent_desired_node_id": NODE_ID,
        "nctl_ssh_host_key_alias": ALIAS,
        "ansible_ssh_common_args": build_ansible_ssh_common_args(ALIAS, str(cfg.resolved_ssh_known_hosts_file())),
        "ansible_host": ansible_host,
    }


def _inventory_payload(cfg: Config, *, host_vars: dict | None = None):
    return {
        "dnsmasq_server": {"hosts": ["agdnsmasq"]},
        "_meta": {"hostvars": {"agdnsmasq": host_vars if host_vars is not None else _valid_host_vars(cfg)}},
    }


def _write_managed_entry(cfg: Config, key_blob: str = KEY_BLOB) -> None:
    path = cfg.resolved_ssh_known_hosts_file()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(f"{ALIAS} ssh-ed25519 {key_blob} nctl:agdnsmasq\n")


def _good_probe(key_blob: str = KEY_BLOB) -> SshProbeRunner:
    def keyscan(host, port, timeout):
        return subprocess.CompletedProcess(args=["ssh-keyscan"], returncode=0, stdout=f"{host} ssh-ed25519 {key_blob}\n", stderr="")

    return SshProbeRunner(
        keyscan=keyscan,
        effective_config=lambda h, p: subprocess.CompletedProcess([], 0, "", ""),
        keygen_find=lambda p, h: subprocess.CompletedProcess([], 0, "", ""),
    )


def test_dry_run_renders_artifact_invokes_check_diff_and_emits_events(tmp_path, monkeypatch):
    cfg = _config(tmp_path)
    _write_managed_entry(cfg)
    calls = []
    monkeypatch.setattr("nctl_core.dnsmasq_apply.build_dnsmasq_render", lambda cfg, operation_id=None: _render(operation_id))
    monkeypatch.setattr("nctl_core.dnsmasq_apply.shutil.which", lambda name: f"/usr/bin/{name}")

    def fake_run(args, cwd, timeout):
        calls.append((args, cwd))
        if args[0] == "ansible-inventory":
            return subprocess.CompletedProcess(args, 0, json.dumps(_inventory_payload(cfg)), "")
        stdout = "PLAY RECAP ***\nagdnsmasq : ok=3 changed=1 unreachable=0 failed=0 skipped=0 rescued=0 ignored=0\n"
        return subprocess.CompletedProcess(args, 0, stdout, "")

    monkeypatch.setattr("nctl_core.ansible._run_command", fake_run)

    envelope = build_dnsmasq_apply(cfg, probe=_good_probe())

    assert envelope.ok is True
    assert envelope.data.mode == "dry-run"
    assert envelope.data.target_hosts == ["agdnsmasq"]
    assert envelope.data.setup.exit_code == 0
    assert envelope.data.ansible.exit_code == 0
    assert envelope.data.ansible.recap["agdnsmasq"]["changed"] == 1
    assert calls[1][0][-2:] == ["--check", "--diff"]
    assert calls[2][0][-2:] == ["--check", "--diff"]
    artifact = cfg.events.resolved_log_dir() / envelope.data.operation_id / "artifacts/dnsmasq-records.conf"
    assert artifact.is_file()
    assert f"# operation_id: {envelope.data.operation_id}" in artifact.read_text()
    events = [json.loads(line)["event"] for line in (cfg.events.resolved_log_dir() / f"{envelope.data.operation_id}.jsonl").read_text().splitlines()]
    assert events == ["started", "rendered", "setup_dry_run_completed", "dry_run_completed", "finished"]


def test_yes_runs_real_apply_without_check_flags(tmp_path, monkeypatch):
    cfg = _config(tmp_path)
    _write_managed_entry(cfg)
    calls = []
    monkeypatch.setattr("nctl_core.dnsmasq_apply.build_dnsmasq_render", lambda cfg, operation_id=None: _render(operation_id))
    monkeypatch.setattr("nctl_core.dnsmasq_apply.shutil.which", lambda name: f"/usr/bin/{name}")

    def fake_run(args, cwd, timeout):
        calls.append(args)
        stdout = json.dumps(_inventory_payload(cfg)) if args[0] == "ansible-inventory" else "agdnsmasq : ok=3 changed=1 unreachable=0 failed=0\n"
        return subprocess.CompletedProcess(args, 0, stdout, "")

    monkeypatch.setattr("nctl_core.ansible._run_command", fake_run)

    envelope = build_dnsmasq_apply(cfg, apply_changes=True, probe=_good_probe())

    assert envelope.ok is True
    assert envelope.data.mode == "apply"
    assert "--check" not in calls[1]
    assert "--diff" not in calls[1]
    assert "--check" not in calls[2]
    assert "--diff" not in calls[2]
    events = [json.loads(line)["event"] for line in (cfg.events.resolved_log_dir() / f"{envelope.data.operation_id}.jsonl").read_text().splitlines()]
    assert events == [
        "started",
        "rendered",
        "setup_started",
        "setup_completed",
        "apply_started",
        "apply_completed",
        "finished",
    ]


def test_empty_dnsmasq_group_is_a_pointed_failure(tmp_path, monkeypatch):
    cfg = _config(tmp_path)
    monkeypatch.setattr("nctl_core.dnsmasq_apply.build_dnsmasq_render", lambda cfg, operation_id=None: _render(operation_id))
    monkeypatch.setattr("nctl_core.dnsmasq_apply.shutil.which", lambda name: f"/usr/bin/{name}")
    monkeypatch.setattr(
        "nctl_core.ansible._run_command",
        lambda args, cwd, timeout: subprocess.CompletedProcess(args, 0, json.dumps({"ssh_hosts": {"hosts": ["agpc"]}}), ""),
    )

    envelope = build_dnsmasq_apply(cfg)

    assert envelope.ok is False
    assert envelope.errors[0].code == "dnsmasq_inventory_group_empty"
    assert envelope.data.ansible is None


def test_missing_inventory_points_to_nctl_production_render(tmp_path, monkeypatch):
    cfg = _config(tmp_path)
    cfg.ansible.resolved_inventory(cfg.source_path.parent).unlink()
    monkeypatch.setattr("nctl_core.dnsmasq_apply.build_dnsmasq_render", lambda cfg, operation_id=None: _render(operation_id))

    envelope = build_dnsmasq_apply(cfg)

    assert envelope.ok is False
    assert envelope.errors[0].code == "ansible_inventory_missing"
    assert "nctl render production --out" in envelope.errors[0].message
    assert "export_nintent_production.yml" not in envelope.errors[0].message


def test_ansible_failure_is_returned_with_exit_code_and_recap(tmp_path, monkeypatch):
    cfg = _config(tmp_path)
    _write_managed_entry(cfg)
    monkeypatch.setattr("nctl_core.dnsmasq_apply.build_dnsmasq_render", lambda cfg, operation_id=None: _render(operation_id))
    monkeypatch.setattr("nctl_core.dnsmasq_apply.shutil.which", lambda name: f"/usr/bin/{name}")

    def fake_run(args, cwd, timeout):
        if args[0] == "ansible-inventory":
            return subprocess.CompletedProcess(args, 0, json.dumps(_inventory_payload(cfg)), "")
        if "setup_dnsmasq.yml" in args[3]:
            return subprocess.CompletedProcess(args, 0, "agdnsmasq : ok=1 changed=0 unreachable=0 failed=0\n", "")
        return subprocess.CompletedProcess(
            args,
            2,
            "agdnsmasq : ok=1 changed=0 unreachable=1 failed=0 skipped=0 rescued=0 ignored=0\n",
            "unreachable",
        )

    monkeypatch.setattr("nctl_core.ansible._run_command", fake_run)

    envelope = build_dnsmasq_apply(cfg, probe=_good_probe())

    assert envelope.ok is False
    assert envelope.errors[0].code == "ansible_dry_run_failed"
    assert envelope.data.setup.exit_code == 0
    assert envelope.data.ansible.exit_code == 2
    assert envelope.data.ansible.recap["agdnsmasq"]["unreachable"] == 1


def test_inventory_override_replaces_configured_inventory(tmp_path, monkeypatch):
    cfg = _config(tmp_path)
    _write_managed_entry(cfg)
    override_inventory = tmp_path / "bootstrap" / "hosts_intent.yml"
    override_inventory.parent.mkdir(parents=True)
    override_inventory.write_text("all: {}\n")
    monkeypatch.setattr("nctl_core.dnsmasq_apply.build_dnsmasq_render", lambda cfg, operation_id=None: _render(operation_id))
    monkeypatch.setattr("nctl_core.dnsmasq_apply.shutil.which", lambda name: f"/usr/bin/{name}")
    calls = []

    def fake_run(args, cwd, timeout):
        calls.append(args)
        if args[0] == "ansible-inventory":
            return subprocess.CompletedProcess(args, 0, json.dumps(_inventory_payload(cfg)), "")
        return subprocess.CompletedProcess(args, 0, "agdnsmasq : ok=1 changed=0 unreachable=0 failed=0\n", "")

    monkeypatch.setattr("nctl_core.ansible._run_command", fake_run)

    envelope = build_dnsmasq_apply(cfg, inventory=override_inventory, probe=_good_probe())

    assert envelope.ok is True
    assert envelope.data.inventory_path == str(override_inventory)
    for call_args in calls:
        assert str(override_inventory) in call_args
    configured_inventory = cfg.ansible.resolved_inventory(cfg.source_path.parent)
    for call_args in calls:
        assert str(configured_inventory) not in call_args


def test_inventory_override_relative_path_resolves_against_cwd_not_playbook_dir(tmp_path, monkeypatch):
    # Regression test: the override must not be interpreted relative to `playbook_dir`, which is
    # the ansible-playbook subprocess's cwd (nctl_core.ansible.AnsibleRunner always runs with
    # cwd=playbook_dir) and is generally a different directory than wherever the user ran `nctl
    # apply dnsmasq --inventory <relative path>` from.
    cfg = _config(tmp_path)
    _write_managed_entry(cfg)
    override_inventory = tmp_path / "bootstrap" / "hosts_intent.yml"
    override_inventory.parent.mkdir(parents=True)
    override_inventory.write_text("all: {}\n")
    monkeypatch.chdir(tmp_path)
    relative_inventory = Path("bootstrap/hosts_intent.yml")
    monkeypatch.setattr("nctl_core.dnsmasq_apply.build_dnsmasq_render", lambda cfg, operation_id=None: _render(operation_id))
    monkeypatch.setattr("nctl_core.dnsmasq_apply.shutil.which", lambda name: f"/usr/bin/{name}")
    calls = []

    def fake_run(args, cwd, timeout):
        calls.append(args)
        if args[0] == "ansible-inventory":
            return subprocess.CompletedProcess(args, 0, json.dumps(_inventory_payload(cfg)), "")
        return subprocess.CompletedProcess(args, 0, "agdnsmasq : ok=1 changed=0 unreachable=0 failed=0\n", "")

    monkeypatch.setattr("nctl_core.ansible._run_command", fake_run)

    envelope = build_dnsmasq_apply(cfg, inventory=relative_inventory, probe=_good_probe())

    assert envelope.ok is True
    assert envelope.data.inventory_path == str(override_inventory.resolve())


def test_inventory_override_missing_file_is_a_pointed_failure(tmp_path, monkeypatch):
    cfg = _config(tmp_path)
    missing_inventory = tmp_path / "does-not-exist.yml"
    monkeypatch.setattr("nctl_core.dnsmasq_apply.build_dnsmasq_render", lambda cfg, operation_id=None: _render(operation_id))
    monkeypatch.setattr("nctl_core.dnsmasq_apply.shutil.which", lambda name: f"/usr/bin/{name}")

    envelope = build_dnsmasq_apply(cfg, inventory=missing_inventory)

    assert envelope.ok is False
    assert envelope.errors[0].code == "ansible_inventory_missing"


def test_inventory_override_rejects_host_without_ssh_trust_vars(tmp_path, monkeypatch):
    cfg = _config(tmp_path)
    override_inventory = tmp_path / "bootstrap" / "hosts_intent.yml"
    override_inventory.parent.mkdir(parents=True)
    override_inventory.write_text("all: {}\n")
    monkeypatch.setattr("nctl_core.dnsmasq_apply.build_dnsmasq_render", lambda cfg, operation_id=None: _render(operation_id))
    monkeypatch.setattr("nctl_core.dnsmasq_apply.shutil.which", lambda name: f"/usr/bin/{name}")

    def fake_run(args, cwd, timeout):
        if args[0] == "ansible-inventory":
            # A hand-written/legacy inventory with no SSH trust host vars at all.
            payload = {"dnsmasq_server": {"hosts": ["agdnsmasq"]}, "_meta": {"hostvars": {"agdnsmasq": {}}}}
            return subprocess.CompletedProcess(args, 0, json.dumps(payload), "")
        return subprocess.CompletedProcess(args, 0, "agdnsmasq : ok=1 changed=0 unreachable=0 failed=0\n", "")

    monkeypatch.setattr("nctl_core.ansible._run_command", fake_run)

    envelope = build_dnsmasq_apply(cfg, inventory=override_inventory)

    assert envelope.ok is False
    assert envelope.errors[0].code == "dnsmasq_inventory_untrusted_host"
    assert "agdnsmasq" in envelope.errors[0].message


def test_default_configured_inventory_is_also_subject_to_the_trust_gate(tmp_path, monkeypatch):
    # fix_sshkey2 Step 4 (bug #4): the configured default inventory used to
    # bypass the trust guard entirely; it now goes through the same
    # validation path as an explicit --inventory override.
    cfg = _config(tmp_path)
    monkeypatch.setattr("nctl_core.dnsmasq_apply.build_dnsmasq_render", lambda cfg, operation_id=None: _render(operation_id))
    monkeypatch.setattr("nctl_core.dnsmasq_apply.shutil.which", lambda name: f"/usr/bin/{name}")

    def fake_run(args, cwd, timeout):
        if args[0] == "ansible-inventory":
            payload = {"dnsmasq_server": {"hosts": ["agdnsmasq"]}, "_meta": {"hostvars": {"agdnsmasq": {}}}}
            return subprocess.CompletedProcess(args, 0, json.dumps(payload), "")
        return subprocess.CompletedProcess(args, 0, "agdnsmasq : ok=1 changed=0 unreachable=0 failed=0\n", "")

    monkeypatch.setattr("nctl_core.ansible._run_command", fake_run)

    envelope = build_dnsmasq_apply(cfg)

    assert envelope.ok is False
    assert envelope.errors[0].code == "dnsmasq_inventory_untrusted_host"
    assert "agdnsmasq" in envelope.errors[0].message


def test_default_configured_inventory_with_a_valid_contract_and_matching_key_proceeds(tmp_path, monkeypatch):
    cfg = _config(tmp_path)
    _write_managed_entry(cfg)
    monkeypatch.setattr("nctl_core.dnsmasq_apply.build_dnsmasq_render", lambda cfg, operation_id=None: _render(operation_id))
    monkeypatch.setattr("nctl_core.dnsmasq_apply.shutil.which", lambda name: f"/usr/bin/{name}")

    def fake_run(args, cwd, timeout):
        if args[0] == "ansible-inventory":
            return subprocess.CompletedProcess(args, 0, json.dumps(_inventory_payload(cfg)), "")
        return subprocess.CompletedProcess(args, 0, "agdnsmasq : ok=1 changed=0 unreachable=0 failed=0\n", "")

    monkeypatch.setattr("nctl_core.ansible._run_command", fake_run)

    envelope = build_dnsmasq_apply(cfg, probe=_good_probe())

    assert envelope.ok is True


def _fake_run_inventory_only(cfg, calls):
    def fake_run(args, cwd, timeout):
        calls.append(args)
        if args[0] == "ansible-inventory":
            return subprocess.CompletedProcess(args, 0, json.dumps(_inventory_payload(cfg)), "")
        return subprocess.CompletedProcess(args, 0, "agdnsmasq : ok=1 changed=0 unreachable=0 failed=0\n", "")

    return fake_run


def test_unenrolled_host_is_rejected_and_invokes_no_ansible_playbook(tmp_path, monkeypatch):
    # No managed known_hosts entry at all -- fix_sshkey2 Step 4 item 4.
    cfg = _config(tmp_path)
    monkeypatch.setattr("nctl_core.dnsmasq_apply.build_dnsmasq_render", lambda cfg, operation_id=None: _render(operation_id))
    monkeypatch.setattr("nctl_core.dnsmasq_apply.shutil.which", lambda name: f"/usr/bin/{name}")
    calls = []
    monkeypatch.setattr("nctl_core.ansible._run_command", _fake_run_inventory_only(cfg, calls))

    envelope = build_dnsmasq_apply(cfg, probe=_good_probe())

    assert envelope.ok is False
    assert envelope.errors[0].code == "ssh_host_key_unenrolled"
    assert envelope.data.ssh_preflight[0]["status"] == "unenrolled"
    assert not any(c[0] == "ansible-playbook" for c in calls)


def test_mismatched_offered_key_is_rejected_and_invokes_no_ansible_playbook(tmp_path, monkeypatch):
    cfg = _config(tmp_path)
    _write_managed_entry(cfg)  # managed store has KEY_BLOB
    monkeypatch.setattr("nctl_core.dnsmasq_apply.build_dnsmasq_render", lambda cfg, operation_id=None: _render(operation_id))
    monkeypatch.setattr("nctl_core.dnsmasq_apply.shutil.which", lambda name: f"/usr/bin/{name}")
    calls = []
    monkeypatch.setattr("nctl_core.ansible._run_command", _fake_run_inventory_only(cfg, calls))

    envelope = build_dnsmasq_apply(cfg, probe=_good_probe(OTHER_KEY_BLOB))  # host now offers a different key

    assert envelope.ok is False
    assert envelope.errors[0].code == "ssh_host_key_mismatch"
    assert not any(c[0] == "ansible-playbook" for c in calls)


def test_unreachable_route_is_rejected(tmp_path, monkeypatch):
    cfg = _config(tmp_path)
    _write_managed_entry(cfg)
    monkeypatch.setattr("nctl_core.dnsmasq_apply.build_dnsmasq_render", lambda cfg, operation_id=None: _render(operation_id))
    monkeypatch.setattr("nctl_core.dnsmasq_apply.shutil.which", lambda name: f"/usr/bin/{name}")
    calls = []

    def fake_run(args, cwd, timeout):
        calls.append(args)
        if args[0] == "ansible-inventory":
            # No ansible_host and no connection_path: nothing to resolve a route from.
            host_vars = {
                "nintent_desired_node_id": NODE_ID,
                "nctl_ssh_host_key_alias": ALIAS,
                "ansible_ssh_common_args": build_ansible_ssh_common_args(ALIAS, str(cfg.resolved_ssh_known_hosts_file())),
            }
            return subprocess.CompletedProcess(args, 0, json.dumps(_inventory_payload(cfg, host_vars=host_vars)), "")
        return subprocess.CompletedProcess(args, 0, "agdnsmasq : ok=1 changed=0 unreachable=0 failed=0\n", "")

    monkeypatch.setattr("nctl_core.ansible._run_command", fake_run)

    envelope = build_dnsmasq_apply(cfg, probe=_good_probe())

    assert envelope.ok is False
    assert envelope.errors[0].code == "ssh_host_key_unreachable"
    assert not any(c[0] == "ansible-playbook" for c in calls)


def test_production_style_host_vars_resolve_route_via_connection_path(tmp_path, monkeypatch):
    # Production inventories never export ansible_host directly (composer
    # pops it); the route must be derivable from connection_path/mdns_hostname
    # the same way production.contract.select_local_route derives it.
    cfg = _config(tmp_path)
    _write_managed_entry(cfg)
    monkeypatch.setattr("nctl_core.dnsmasq_apply.build_dnsmasq_render", lambda cfg, operation_id=None: _render(operation_id))
    monkeypatch.setattr("nctl_core.dnsmasq_apply.shutil.which", lambda name: f"/usr/bin/{name}")

    def fake_run(args, cwd, timeout):
        if args[0] == "ansible-inventory":
            host_vars = {
                "nintent_desired_node_id": NODE_ID,
                "nctl_ssh_host_key_alias": ALIAS,
                "ansible_ssh_common_args": build_ansible_ssh_common_args(ALIAS, str(cfg.resolved_ssh_known_hosts_file())),
                "connection_path": "local",
                "mdns_hostname": "agdnsmasq.local",
            }
            return subprocess.CompletedProcess(args, 0, json.dumps(_inventory_payload(cfg, host_vars=host_vars)), "")
        return subprocess.CompletedProcess(args, 0, "agdnsmasq : ok=1 changed=0 unreachable=0 failed=0\n", "")

    monkeypatch.setattr("nctl_core.ansible._run_command", fake_run)

    scanned = []

    def keyscan(host, port, timeout):
        scanned.append(host)
        return subprocess.CompletedProcess(args=["ssh-keyscan"], returncode=0, stdout=f"{host} ssh-ed25519 {KEY_BLOB}\n", stderr="")

    probe = SshProbeRunner(keyscan=keyscan, effective_config=lambda h, p: subprocess.CompletedProcess([], 0, "", ""), keygen_find=lambda p, h: subprocess.CompletedProcess([], 0, "", ""))

    envelope = build_dnsmasq_apply(cfg, probe=probe)

    assert envelope.ok is True, envelope.errors
    assert scanned == ["agdnsmasq.local"]


def test_unrendered_jinja_ansible_host_falls_back_to_connection_path_chain(tmp_path, monkeypatch):
    # Regression (caught live against real Nautobot data during Step 5
    # verification): `ansible-inventory --host` reports every production
    # host's `ansible_host` as inherited, *unrendered* from group_vars/all's
    # Jinja template ("{{ tailscale_ip | default(...) }}"), not a resolved
    # address -- ansible-inventory does not template variables. Using that
    # string verbatim caused a real `ssh-keyscan ... getaddrinfo {{:`
    # failure. The literal `{{...}}` string must never be treated as a route;
    # it must fall through to the connection_path chain instead.
    cfg = _config(tmp_path)
    _write_managed_entry(cfg)
    monkeypatch.setattr("nctl_core.dnsmasq_apply.build_dnsmasq_render", lambda cfg, operation_id=None: _render(operation_id))
    monkeypatch.setattr("nctl_core.dnsmasq_apply.shutil.which", lambda name: f"/usr/bin/{name}")

    def fake_run(args, cwd, timeout):
        if args[0] == "ansible-inventory":
            host_vars = {
                "nintent_desired_node_id": NODE_ID,
                "nctl_ssh_host_key_alias": ALIAS,
                "ansible_ssh_common_args": build_ansible_ssh_common_args(ALIAS, str(cfg.resolved_ssh_known_hosts_file())),
                "ansible_host": (
                    "{{\n  tailscale_ip | default(local_connection_host, true)\n"
                    "  if connection_path == 'tailscale'\n  else local_connection_host\n}}"
                ),
                "connection_path": "local",
                "local_ip": "192.168.0.2",
                "mdns_hostname": "agdnsmasq.local",
            }
            return subprocess.CompletedProcess(args, 0, json.dumps(_inventory_payload(cfg, host_vars=host_vars)), "")
        return subprocess.CompletedProcess(args, 0, "agdnsmasq : ok=1 changed=0 unreachable=0 failed=0\n", "")

    monkeypatch.setattr("nctl_core.ansible._run_command", fake_run)

    scanned = []

    def keyscan(host, port, timeout):
        scanned.append(host)
        return subprocess.CompletedProcess(args=["ssh-keyscan"], returncode=0, stdout=f"{host} ssh-ed25519 {KEY_BLOB}\n", stderr="")

    probe = SshProbeRunner(keyscan=keyscan, effective_config=lambda h, p: subprocess.CompletedProcess([], 0, "", ""), keygen_find=lambda p, h: subprocess.CompletedProcess([], 0, "", ""))

    envelope = build_dnsmasq_apply(cfg, probe=probe)

    assert envelope.ok is True, envelope.errors
    assert scanned == ["192.168.0.2"]  # local_ip wins over mdns_hostname, never the raw "{{...}}" string


def test_non_empty_alias_differing_from_uuid_derived_value_is_rejected(tmp_path, monkeypatch):
    cfg = _config(tmp_path)
    monkeypatch.setattr("nctl_core.dnsmasq_apply.build_dnsmasq_render", lambda cfg, operation_id=None: _render(operation_id))
    monkeypatch.setattr("nctl_core.dnsmasq_apply.shutil.which", lambda name: f"/usr/bin/{name}")

    def fake_run(args, cwd, timeout):
        if args[0] == "ansible-inventory":
            host_vars = {
                "nintent_desired_node_id": NODE_ID,
                "nctl_ssh_host_key_alias": "nctl-node-hand-written-alias",
                "ansible_ssh_common_args": build_ansible_ssh_common_args("nctl-node-hand-written-alias", str(cfg.resolved_ssh_known_hosts_file())),
                "ansible_host": "192.0.2.10",
            }
            return subprocess.CompletedProcess(args, 0, json.dumps(_inventory_payload(cfg, host_vars=host_vars)), "")
        return subprocess.CompletedProcess(args, 0, "agdnsmasq : ok=1 changed=0 unreachable=0 failed=0\n", "")

    monkeypatch.setattr("nctl_core.ansible._run_command", fake_run)

    envelope = build_dnsmasq_apply(cfg, probe=_good_probe())

    assert envelope.ok is False
    assert envelope.errors[0].code == "dnsmasq_inventory_untrusted_host"
    assert "ssh_host_key_alias_mismatch" in envelope.errors[0].message


def test_policy_weakening_ansible_ssh_common_args_is_rejected(tmp_path, monkeypatch):
    # A non-strict extra option (or a missing one) must not merely be
    # tolerated as "contains the right options" -- the whole string must
    # equal the closed, controller-generated policy exactly.
    cfg = _config(tmp_path)
    monkeypatch.setattr("nctl_core.dnsmasq_apply.build_dnsmasq_render", lambda cfg, operation_id=None: _render(operation_id))
    monkeypatch.setattr("nctl_core.dnsmasq_apply.shutil.which", lambda name: f"/usr/bin/{name}")

    def fake_run(args, cwd, timeout):
        if args[0] == "ansible-inventory":
            weakened = build_ansible_ssh_common_args(ALIAS, str(cfg.resolved_ssh_known_hosts_file())) + " -o StrictHostKeyChecking=no"
            host_vars = {
                "nintent_desired_node_id": NODE_ID,
                "nctl_ssh_host_key_alias": ALIAS,
                "ansible_ssh_common_args": weakened,
                "ansible_host": "192.0.2.10",
            }
            return subprocess.CompletedProcess(args, 0, json.dumps(_inventory_payload(cfg, host_vars=host_vars)), "")
        return subprocess.CompletedProcess(args, 0, "agdnsmasq : ok=1 changed=0 unreachable=0 failed=0\n", "")

    monkeypatch.setattr("nctl_core.ansible._run_command", fake_run)

    envelope = build_dnsmasq_apply(cfg, probe=_good_probe())

    assert envelope.ok is False
    assert envelope.errors[0].code == "dnsmasq_inventory_untrusted_host"
    assert "ansible_ssh_common_args_mismatch" in envelope.errors[0].message


def test_missing_ansible_ssh_common_args_is_rejected(tmp_path, monkeypatch):
    cfg = _config(tmp_path)
    monkeypatch.setattr("nctl_core.dnsmasq_apply.build_dnsmasq_render", lambda cfg, operation_id=None: _render(operation_id))
    monkeypatch.setattr("nctl_core.dnsmasq_apply.shutil.which", lambda name: f"/usr/bin/{name}")

    def fake_run(args, cwd, timeout):
        if args[0] == "ansible-inventory":
            host_vars = {
                "nintent_desired_node_id": NODE_ID,
                "nctl_ssh_host_key_alias": ALIAS,
                "ansible_host": "192.0.2.10",
            }
            return subprocess.CompletedProcess(args, 0, json.dumps(_inventory_payload(cfg, host_vars=host_vars)), "")
        return subprocess.CompletedProcess(args, 0, "agdnsmasq : ok=1 changed=0 unreachable=0 failed=0\n", "")

    monkeypatch.setattr("nctl_core.ansible._run_command", fake_run)

    envelope = build_dnsmasq_apply(cfg, probe=_good_probe())

    assert envelope.ok is False
    assert envelope.errors[0].code == "dnsmasq_inventory_untrusted_host"
    assert "ansible_ssh_common_args_mismatch" in envelope.errors[0].message


def test_dry_run_performs_the_same_preflight_and_never_mutates_trust(tmp_path, monkeypatch):
    cfg = _config(tmp_path)
    _write_managed_entry(cfg)
    known_hosts_path = cfg.resolved_ssh_known_hosts_file()
    before = known_hosts_path.read_text()
    monkeypatch.setattr("nctl_core.dnsmasq_apply.build_dnsmasq_render", lambda cfg, operation_id=None: _render(operation_id))
    monkeypatch.setattr("nctl_core.dnsmasq_apply.shutil.which", lambda name: f"/usr/bin/{name}")

    def fake_run(args, cwd, timeout):
        if args[0] == "ansible-inventory":
            return subprocess.CompletedProcess(args, 0, json.dumps(_inventory_payload(cfg)), "")
        return subprocess.CompletedProcess(args, 0, "agdnsmasq : ok=1 changed=0 unreachable=0 failed=0\n", "")

    monkeypatch.setattr("nctl_core.ansible._run_command", fake_run)

    envelope = build_dnsmasq_apply(cfg, apply_changes=False, probe=_good_probe())

    assert envelope.ok is True
    assert envelope.data.ssh_preflight[0]["status"] == "ready"
    assert known_hosts_path.read_text() == before


def test_ssh_preflight_summary_is_populated_on_success(tmp_path, monkeypatch):
    cfg = _config(tmp_path)
    _write_managed_entry(cfg)
    monkeypatch.setattr("nctl_core.dnsmasq_apply.build_dnsmasq_render", lambda cfg, operation_id=None: _render(operation_id))
    monkeypatch.setattr("nctl_core.dnsmasq_apply.shutil.which", lambda name: f"/usr/bin/{name}")

    def fake_run(args, cwd, timeout):
        if args[0] == "ansible-inventory":
            return subprocess.CompletedProcess(args, 0, json.dumps(_inventory_payload(cfg)), "")
        return subprocess.CompletedProcess(args, 0, "agdnsmasq : ok=1 changed=0 unreachable=0 failed=0\n", "")

    monkeypatch.setattr("nctl_core.ansible._run_command", fake_run)

    envelope = build_dnsmasq_apply(cfg, probe=_good_probe())

    assert envelope.ok is True
    assert envelope.data.ssh_preflight == [{"slug": "agdnsmasq", "alias": ALIAS, "status": "ready", "detail": ""}]


def test_setup_failure_aborts_before_records_deploy(tmp_path, monkeypatch):
    cfg = _config(tmp_path)
    _write_managed_entry(cfg)
    monkeypatch.setattr("nctl_core.dnsmasq_apply.build_dnsmasq_render", lambda cfg, operation_id=None: _render(operation_id))
    monkeypatch.setattr("nctl_core.dnsmasq_apply.shutil.which", lambda name: f"/usr/bin/{name}")
    calls = []

    def fake_run(args, cwd, timeout):
        calls.append(args)
        if args[0] == "ansible-inventory":
            return subprocess.CompletedProcess(args, 0, json.dumps(_inventory_payload(cfg)), "")
        return subprocess.CompletedProcess(
            args, 1, "agdnsmasq : ok=0 changed=0 unreachable=1 failed=1\n", "setup failed"
        )

    monkeypatch.setattr("nctl_core.ansible._run_command", fake_run)

    envelope = build_dnsmasq_apply(cfg, probe=_good_probe())

    assert envelope.ok is False
    assert envelope.errors[0].code == "ansible_setup_dry_run_failed"
    assert envelope.data.setup.exit_code == 1
    assert envelope.data.ansible is None
    assert len(calls) == 2, "the records deploy playbook must not run after a setup failure"


def test_inventory_group_hosts_includes_child_groups():
    payload = {
        "dnsmasq_server": {"children": ["primary_dns"]},
        "primary_dns": {"hosts": ["dns-1", "dns-2"]},
    }
    assert _inventory_group_hosts(payload, "dnsmasq_server") == {"dns-1", "dns-2"}


def test_parse_recap_ignores_non_recap_lines():
    assert _parse_recap("TASK [x] ***\nhost-a : ok=2 changed=1 unreachable=0 failed=0\n") == {
        "host-a": {"ok": 2, "changed": 1, "unreachable": 0, "failed": 0}
    }
