from __future__ import annotations

import subprocess
from pathlib import Path
from types import SimpleNamespace

import yaml

import nctl_core.hosts_intent_render as hosts_intent_render
from nctl_core.hosts_intent_render import (
    HostsIntentRenderData,
    build_hosts_intent_render,
    write_hosts_intent_artifacts,
)
from nctl_core.output import Envelope, EnvelopeError
from nctl_core.sources.desired import DesiredEndpoint, DesiredNode, DesiredSnapshot

SCHEMA = "nctl.render.hosts_intent.v1"


NODE_1_ID = "11111111-1111-1111-1111-111111111111"
NODE_2_ID = "22222222-2222-2222-2222-222222222222"


def _snapshot() -> DesiredSnapshot:
    return DesiredSnapshot(
        nodes=[
            DesiredNode(id=NODE_1_ID, slug="agnode", name="ag Node", lifecycle="active", node_type="device"),
            DesiredNode(id=NODE_2_ID, slug="no-mdns", name="No mDNS", lifecycle="active", node_type="device"),
        ],
        endpoints=[
            DesiredEndpoint(
                id="endpoint-1",
                name="primary",
                endpoint_type="primary",
                node_id=NODE_1_ID,
                node_slug="agnode",
                mdns_name="agnode.local",
            ),
        ],
    )


def _fake_config() -> SimpleNamespace:
    return SimpleNamespace(
        nautobot=SimpleNamespace(url="http://nautobot.test", resolve_token=lambda: "token"),
        ansible=SimpleNamespace(resolved_playbook_dir=lambda config_dir: Path("/fake/playbook-dir")),
        ssh=SimpleNamespace(resolved_known_hosts_file=lambda: Path("/fake/state/ssh/known_hosts")),
        source_path=Path("/fake/nctl.toml"),
    )


def test_build_hosts_intent_render_produces_inventory_and_skips(monkeypatch):
    monkeypatch.setattr(hosts_intent_render, "NautobotClient", lambda url, token: SimpleNamespace(close=lambda: None))
    monkeypatch.setattr(hosts_intent_render, "fetch_desired_snapshot", lambda client: _snapshot())
    monkeypatch.setattr(hosts_intent_render, "load_deployment_profiles", lambda playbook_dir: ({}, "digest"))

    envelope = build_hosts_intent_render(_fake_config())

    assert envelope.ok
    assert envelope.schema_name == SCHEMA
    assert envelope.data.schema_version == "5.0"
    assert envelope.data.summary["exported_hosts"] == 1
    assert envelope.data.summary["skipped_nodes"] == 1
    assert envelope.data.skipped[0]["reasons"] == ["missing_mdns_name"]
    loaded = yaml.safe_load(envelope.data.inventory_yaml)
    agnode = loaded["all"]["children"]["ssh_hosts"]["hosts"]["agnode"]
    assert agnode["mdns_hostname"] == "agnode.local"
    assert agnode["nctl_ssh_host_key_alias"] == f"nctl-node-{NODE_1_ID}"
    assert "HostKeyAlias=nctl-node-" + NODE_1_ID in agnode["ansible_ssh_common_args"]
    assert "/fake/state/ssh/known_hosts" in agnode["ansible_ssh_common_args"]


def test_build_hosts_intent_render_fails_on_invalid_deployment_profiles(monkeypatch):
    monkeypatch.setattr(hosts_intent_render, "NautobotClient", lambda url, token: SimpleNamespace(close=lambda: None))
    monkeypatch.setattr(hosts_intent_render, "fetch_desired_snapshot", lambda client: _snapshot())

    def _boom(playbook_dir):
        raise hosts_intent_render.DeploymentProfilesError("cannot read deployment_profiles.yml")

    monkeypatch.setattr(hosts_intent_render, "load_deployment_profiles", _boom)

    envelope = build_hosts_intent_render(_fake_config())

    assert not envelope.ok
    assert envelope.errors[0].code == "deployment_profiles_invalid"


def _ok_envelope() -> Envelope[HostsIntentRenderData]:
    data = HostsIntentRenderData(
        inventory_yaml="# Generated by nctl\nall:\n  children: {}\n",
        export_json='{"schema_version": "4.0"}\n',
    )
    return Envelope.build(SCHEMA, data, [])


def test_write_hosts_intent_artifacts_propagates_render_failure(tmp_path):
    envelope = Envelope.build(
        SCHEMA, HostsIntentRenderData(), [EnvelopeError(code="nautobot_fetch_failed", message="boom")]
    )

    error = write_hosts_intent_artifacts(envelope, tmp_path)

    assert error is not None
    assert error.code == "nautobot_fetch_failed"


def test_write_hosts_intent_artifacts_atomically_replaces_on_success(tmp_path, monkeypatch):
    monkeypatch.setattr("nctl_core.inventory_write.shutil.which", lambda name: "/usr/bin/ansible-inventory")
    monkeypatch.setattr(
        "nctl_core.inventory_write.subprocess.run",
        lambda *a, **kw: subprocess.CompletedProcess(args=a, returncode=0, stdout="{}", stderr=""),
    )

    error = write_hosts_intent_artifacts(_ok_envelope(), tmp_path)

    assert error is None
    assert (tmp_path / "hosts_intent.yml").read_text().startswith("# Generated by nctl")
    assert (tmp_path / "hosts-intent-export.json").read_text() == '{"schema_version": "4.0"}\n'
    assert list(tmp_path.glob(".hosts_intent.yml.*.tmp")) == []


def test_write_hosts_intent_artifacts_preserves_previous_file_on_invalid(tmp_path, monkeypatch):
    monkeypatch.setattr("nctl_core.inventory_write.shutil.which", lambda name: "/usr/bin/ansible-inventory")
    monkeypatch.setattr(
        "nctl_core.inventory_write.subprocess.run",
        lambda *a, **kw: subprocess.CompletedProcess(args=a, returncode=1, stdout="", stderr="boom"),
    )
    previous = tmp_path / "hosts_intent.yml"
    previous.write_text("# previous\n")

    error = write_hosts_intent_artifacts(_ok_envelope(), tmp_path)

    assert error is not None
    assert error.code == "ansible_inventory_invalid"
    assert previous.read_text() == "# previous\n"
    assert not (tmp_path / "hosts-intent-export.json").exists()
    assert list(tmp_path.glob(".hosts_intent.yml.*.tmp")) == []
