import json

from typer.testing import CliRunner

import nctl_core.cli.main as main
from nctl_core.hosts_intent_render import HostsIntentRenderData
from nctl_core.output import Envelope, EnvelopeError

runner = CliRunner()

SCHEMA = "nctl.render.hosts_intent.v1"


def _ok_envelope() -> Envelope[HostsIntentRenderData]:
    data = HostsIntentRenderData(
        schema_version="3.0",
        summary={"total_nodes": 2, "exported_hosts": 1, "skipped_nodes": 1, "groups": ["ssh_hosts"]},
        inventory={"all": {"children": {"ssh_hosts": {"hosts": {"agnode": {}}}}}},
        hosts=[{"inventory_hostname": "agnode"}],
        skipped=[{"desired_node_slug": "no-mdns", "reasons": ["missing_mdns_name"]}],
        inventory_yaml="# Generated by nctl\nall:\n  children: {}\n",
        export_json='{"schema_version": "3.0"}\n',
    )
    return Envelope.build(SCHEMA, data, [])


def _failed_envelope() -> Envelope[HostsIntentRenderData]:
    return Envelope.build(
        SCHEMA, HostsIntentRenderData(), [EnvelopeError(code="nautobot_fetch_failed", message="boom")]
    )


def test_render_hosts_intent_default_prints_inventory_yaml_to_stdout(monkeypatch):
    monkeypatch.setattr(main, "_load_config", lambda path: object())
    monkeypatch.setattr(main, "build_hosts_intent_render", lambda cfg: _ok_envelope())

    result = runner.invoke(main.app, ["render", "hosts-intent"])

    assert result.exit_code == 0
    assert "# Generated by nctl" in result.stdout


def test_render_hosts_intent_json_prints_envelope(monkeypatch):
    monkeypatch.setattr(main, "_load_config", lambda path: object())
    monkeypatch.setattr(main, "build_hosts_intent_render", lambda cfg: _ok_envelope())

    result = runner.invoke(main.app, ["render", "hosts-intent", "--json"])

    assert result.exit_code == 0
    payload = json.loads(result.stdout)
    assert payload["schema"] == SCHEMA
    assert payload["data"]["summary"]["exported_hosts"] == 1


def test_render_hosts_intent_out_writes_artifacts_and_prints_summary(tmp_path, monkeypatch):
    monkeypatch.setattr(main, "_load_config", lambda path: object())
    monkeypatch.setattr(main, "build_hosts_intent_render", lambda cfg: _ok_envelope())
    monkeypatch.setattr(main, "write_hosts_intent_artifacts", lambda envelope, out: None)

    result = runner.invoke(main.app, ["render", "hosts-intent", "--out", str(tmp_path)])

    assert result.exit_code == 0
    assert "exported_hosts: 1" in result.stdout
    assert "# Generated by nctl" not in result.stdout


def test_render_hosts_intent_out_reports_write_failure(tmp_path, monkeypatch):
    monkeypatch.setattr(main, "_load_config", lambda path: object())
    monkeypatch.setattr(main, "build_hosts_intent_render", lambda cfg: _ok_envelope())
    monkeypatch.setattr(
        main,
        "write_hosts_intent_artifacts",
        lambda envelope, out: EnvelopeError(code="ansible_inventory_invalid", message="bad inventory"),
    )

    result = runner.invoke(main.app, ["render", "hosts-intent", "--out", str(tmp_path)])

    assert result.exit_code == 1
    assert "error [ansible_inventory_invalid]" in result.stdout


def test_render_hosts_intent_exit_1_on_failure(monkeypatch):
    monkeypatch.setattr(main, "_load_config", lambda path: object())
    monkeypatch.setattr(main, "build_hosts_intent_render", lambda cfg: _failed_envelope())

    result = runner.invoke(main.app, ["render", "hosts-intent"])

    assert result.exit_code == 1
    assert "error [nautobot_fetch_failed]" in result.stdout
