import json

import httpx
import respx

from nctl_core.config import Config
from nctl_core.dnsmasq_render import (
    build_dnsmasq_render,
    render_dnsmasq_conf_text,
    render_dnsmasq_summary_text,
)
from nctl_core.nautobot import NautobotConnectionError

BASE_URL = "http://nautobot.test"

EMPTY_DESIRED_RESPONSE = {
    "data": {
        "desired_nodes": [],
        "desired_endpoints": [],
        "desired_ip_ranges": [],
        "desired_node_operational_configs": [],
        "desired_service_placements": [],
        "desired_services": [],
        "desired_dependencies": [],
    }
}

EMPTY_ACTUAL_RESPONSE = {
    "data": {
        "devices": [],
        "virtual_machines": [],
        "interfaces": [],
        "ip_addresses": [],
    }
}

ONE_ENDPOINT_DESIRED_RESPONSE = {
    "data": {
        "desired_nodes": [
            {
                "id": "node-1",
                "slug": "edge-1",
                "name": "Edge 1",
                "lifecycle": "ACTIVE",
                "node_type": "DEVICE",
                "role": None,
                "accepted_actual_types": ["DEVICE"],
                "expected_spec": {},
                "realized_device": None,
                "realized_vm": None,
            }
        ],
        "desired_endpoints": [
            {
                "id": "endpoint-1",
                "name": "primary",
                "endpoint_type": "PRIMARY",
                "ip_address": "192.0.2.10/32",
                "ip_policy": "STATIC",
                "dns_name": "edge-1.example.test",
                "mdns_name": "edge-1.local",
                "vpn_dns_name": None,
                "protocol": None,
                "port": None,
                "generate_dnsmasq": True,
                "dnsmasq_record_type": "HOST_RECORD",
                "realized_ip_address": None,
                "desired_node": {"id": "node-1", "slug": "edge-1"},
            }
        ],
        "desired_ip_ranges": [],
        "desired_node_operational_configs": [],
        "desired_service_placements": [],
        "desired_services": [],
        "desired_dependencies": [],
    }
}


def make_config(tmp_path) -> Config:
    config_path = tmp_path / "nctl.toml"
    config_path.write_text(
        f"""
[nautobot]
url = "{BASE_URL}"

[inventory]
dumps_dir = "{tmp_path / 'dumps'}"

[ansible]
playbook_dir = "{tmp_path / 'ansible_agdev'}"
inventory = "inventories/generated/hosts_intent.yml"
"""
    )
    return Config.load(config_path)


def _mock_graphql(desired_response, actual_response=EMPTY_ACTUAL_RESPONSE):
    respx.post(f"{BASE_URL}/api/graphql/").mock(
        side_effect=[
            httpx.Response(200, json=desired_response),
            httpx.Response(200, json=actual_response),
        ]
    )


@respx.mock
def test_build_dnsmasq_render_ok_with_one_endpoint(tmp_path):
    _mock_graphql(ONE_ENDPOINT_DESIRED_RESPONSE)
    cfg = make_config(tmp_path)

    envelope = build_dnsmasq_render(cfg)

    assert envelope.ok is True
    assert envelope.schema_name == "nctl.render.dnsmasq.v1"
    assert envelope.data.schema_version == "4.0"
    assert envelope.data.summary["dns_records"] == 1
    assert "host-record=edge-1.example.test,192.0.2.10" in envelope.data.conf
    assert "# Generated by nctl" in envelope.data.conf
    assert "# operation_id" not in envelope.data.conf


@respx.mock
def test_build_dnsmasq_render_empty_desired_state(tmp_path):
    _mock_graphql(EMPTY_DESIRED_RESPONSE)
    cfg = make_config(tmp_path)

    envelope = build_dnsmasq_render(cfg)

    assert envelope.ok is True
    assert envelope.data.summary["total_endpoints"] == 0
    assert envelope.data.dns_records == []


@respx.mock
def test_build_dnsmasq_render_embeds_operation_id_when_requested(tmp_path):
    _mock_graphql(EMPTY_DESIRED_RESPONSE)
    cfg = make_config(tmp_path)

    envelope = build_dnsmasq_render(cfg, operation_id="01JTESTOPERATION00000000000")

    assert "# operation_id: 01JTESTOPERATION00000000000" in envelope.data.conf


def test_build_dnsmasq_render_degrades_on_nautobot_failure(tmp_path, monkeypatch):
    cfg = make_config(tmp_path)

    class FailingClient:
        def __init__(self, *a, **kw):
            pass

        def graphql(self, *a, **kw):
            raise NautobotConnectionError("connection refused")

        def close(self):
            pass

    monkeypatch.setattr("nctl_core.dnsmasq_render.NautobotClient", FailingClient)

    envelope = build_dnsmasq_render(cfg)

    assert envelope.ok is False
    assert any(err.code == "nautobot_fetch_failed" for err in envelope.errors)


def test_render_dnsmasq_conf_text_returns_error_lines_when_not_ok(tmp_path, monkeypatch):
    cfg = make_config(tmp_path)

    class FailingClient:
        def __init__(self, *a, **kw):
            pass

        def graphql(self, *a, **kw):
            raise NautobotConnectionError("connection refused")

        def close(self):
            pass

    monkeypatch.setattr("nctl_core.dnsmasq_render.NautobotClient", FailingClient)
    envelope = build_dnsmasq_render(cfg)

    text = render_dnsmasq_conf_text(envelope)

    assert "error [nautobot_fetch_failed]" in text


@respx.mock
def test_render_dnsmasq_summary_text_reports_counts(tmp_path):
    _mock_graphql(ONE_ENDPOINT_DESIRED_RESPONSE)
    cfg = make_config(tmp_path)
    envelope = build_dnsmasq_render(cfg)

    text = render_dnsmasq_summary_text(envelope)

    assert "dns_records: 1" in text


@respx.mock
def test_envelope_json_round_trips_expected_keys(tmp_path):
    _mock_graphql(ONE_ENDPOINT_DESIRED_RESPONSE)
    cfg = make_config(tmp_path)
    envelope = build_dnsmasq_render(cfg)

    parsed = json.loads(envelope.to_json())

    assert parsed["schema"] == "nctl.render.dnsmasq.v1"
    assert set(parsed["data"].keys()) == {
        "schema_version",
        "summary",
        "dns_records",
        "dhcp_reservations",
        "dhcp_ranges",
        "skipped",
        "conf",
    }
